# -------------------------------------------------------------------------------------
# --------------------- Day 4: A* is Born (Thu. Apr. 17th) ----------------------------
# -------------------------------------------------------------------------------------
# BEWARE: The initial and goal positions for evaluation will not be the same as
#         they are below to prevent hard-coding.

# --- ros setup ---
team_assignments:
  "zeus": "blue"
quad_state_topics:
  "zeus": "/zeus/state"
proposed_trajectory_topics:
  "zeus": "/zeus/proposed_trajectory"
updated_trajectory_topics:
  "zeus": "/zeus/updated_trajectory"
visualization_trajectory_topics:
  "zeus": "/zeus/visualization_trajectory"
balloon_status_topics:
  "red": "/game_engine/red_balloon_status"
  "blue": "/game_engine/blue_balloon_status"
balloon_position_topics:
  "red": "/game_engine/red_balloon_position"
  "blue": "/game_engine/blue_balloon_position"
goal_status_topics:
  "home": "/game_engine/home_status"

# --- map and meshes --- 
map_file_path: "/home/aeronaut/Workspace/game-engine/resources/maps/uturn.map"
quad_mesh_file_path: "file:///home/aeronaut/Workspace/game-engine/resources/meshes/quad.stl"
balloon_mesh_file_path: "file:///home/aeronaut/Workspace/game-engine/resources/meshes/balloon.stl"
goal_mesh_file_path: "file:///home/aeronaut/Workspace/game-engine/resources/meshes/torus.stl"

# --- quad start and goal positions ---
initial_quad_positions:
  "zeus": "-18.47 18.75 -2.65"
goal_position: [-22.45,19.08,-2.65]

# --- balloon positions ---
red_balloon_position:  [-12.51,17.95,-4.15]
move_red: false 
path_red: false
curve_red: false
red_balloon_position_new:  [-16.6, 17.5, -3.3]
red_balloon_max_move_time: 5.0

blue_balloon_position: [-14.81,14.43,-2.15]
move_blue: false
path_blue: false
curve_blue: false
blue_balloon_position_new: [-14.6, 14.52, -2.3]
blue_balloon_max_move_time: 5.0

use_seed: true
seed: 37

# Balloon Behaviour Booleans
# For teleportation        move:true, path:false, curve:either   (max_move_time describes the maximum amount of time it will take before teleportation)
# For straight line path   move:true, path:true,  curve:false    (max_move_time describes the amount of time it will take to move between two points)
# For ellipse path         move:true, path:true,  curve:true     (max move time describes the period of the ellipse the balloon will take)
# If move is false, balloon will remain motionless

# --- environment and options ---
# 0: zero, 1: mild, 2: stiff, 3: intense, 4: ludicrous
wind_intensity: 0
# revision mode
# 0: NONE, 1: TIME, 2: SHAPE, 3: WAYPOINT
revision_mode: 0
# quad safety limits
# 0: leisure, 1: sport, 2: extreme
quad_safety_limits: 0
# change to true if running in joy stick mode
joy_mode: false
# change to true if using the camera
camera_mode: false
